services:
  - name: frontend
    image: mycompany/frontend:{{PR_NUMBER}}
    port: 3000
    ingress:
      enabled: true
      path: "/"
    env:
      REACT_APP_API_URL: http://your-host/pr-{{PR_NUMBER}}/api

  - name: backend
    image: mycompany/backend:{{PR_NUMBER}}
    port: 5000
    ingress:
      enabled: true
      path: "/api"
    env:
      DATABASE_URL: postgresql://postgres:password@database:5432/myapp
      NODE_ENV: production
      PORT: "5000"

  - name: database
    image: postgres:15-alpine
    port: 5432
    ingress:
      enabled: false
    env:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
